kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-proxy-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: open-cluster-management:cluster-proxy-addon:agent
subjects:
  - kind: ServiceAccount
    name: cluster-proxy-agent-sa
    namespace: {{ .AddonInstallNamespace }}
