apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: open-cluster-management:cluster-proxy-addon:agent
rules:
# Allow cluster-proxy-addon agent to run with openshift library-go
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]

