apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: anp-server
  name: anp-server
  namespace: open-cluster-management
spec:
  selector:
    matchLabels:
      app: anp-server
  template:
    metadata:
      labels:
        app: anp-server
    spec:
      containers:
        - name: proxy-server
          image: quay.io/open-cluster-management/cluster-proxy-addon:latest
          command:
            - "/proxy-server"
            - "--mode=http-connect"
            - "--agent-port=9091"
            - "--server-port=0"
            - "--cluster-ca-cert=/ca/ca-bundle.crt"
            - "--cluster-cert=/tls/tls.crt"
            - "--cluster-key=/tls/tls.key"
            - "--proxy-strategies=destHost"
            - "--uds-name=/cluster-proxy-addon-socket"
            - "--delete-existing-uds-file=true"
          volumeMounts:
            - name: tls-vol
              mountPath: /tls
              readOnly: true
            - name: ca-vol
              mountPath: /ca
              readOnly: true
          ports:
            - name: agentport
              containerPort: 9091
        - name: user-proxy
          image: quay.io/open-cluster-management/cluster-proxy-addon:latest
          imagePullPolicy: IfNotPresent
          command:
            - "/user-proxy"
            - "--server-port=9092"
            - "--server-key=/tls/tls.key"
            - "--server-cert=/tls/tls.crt"
            - "--proxy-uds=/cluster-proxy-addon-socket"
          volumeMounts:
            - name: tls-vol
              mountPath: /tls
              readOnly: true
          ports:
            - name: userport
              containerPort: 9092
      volumes:
        - name: tls-vol
          secret:
            secretName: cluster-proxy-addon-serving-cert
        - name: ca-vol
          configMap:
            name: cluster-proxy-ca-bundle
