apiVersion: v1
kind: Service
metadata:
  name: cluster-proxy-addon-anp
  namespace: open-cluster-management
spec:
  ports:
    - name: agentport
      port: 9091
    - name: userport
      port: 9092
  selector:
    app: anp-server
